export enum FILE_TYPE {
  PLAN_REMIND = 'PLAN_REMIND',
  REPORT = 'REPORT',
  QA = 'QA',
  TEST_CASE = 'TEST_CASE',
  TEST_REVIEW = 'TEST_REVIEW',
  EXCUTE_TEST = 'EXCUTE_TEST',
  MAINTANCE_TEST = 'MAINTANCE_TEST',
  PROJECT_PLAN = 'PROJECT_PLAN',
  PROJECT_REQUIRE = 'PROJECT_REQUIRE',
}
